version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: syncpad
    main: ./cmd/syncpad
    binary: syncpad
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w

archives:
  - id: syncpad
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^chore(deps)"
      - "^Merge"
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
    - title: Chores
      regexp: "^chore"
      order: 2
    - title: Docs
      regexp: "^docs"
      order: 3